#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Design Token Exporter - Export tokens to CSS/JSON/Tailwind/SCSS/LESS formats
设计令牌导出器

Supports multiple output formats:
- CSS: CSS custom properties
- JSON: Raw JSON tokens
- Tailwind: Tailwind CSS configuration
- SCSS: SCSS variables
- LESS: LESS variables
"""

import json
from pathlib import Path
from typing import Optional, Dict, Any, List


class DesignExporter:
    """Export design tokens to various formats."""

    def __init__(self, input_file: Optional[str] = None, output_dir: str = ".",
                 formats: Optional[List[str]] = None,
                 preset: Optional[str] = None):
        self.input_file = input_file
        self.output_dir = output_dir
        self.formats = formats or ["css", "json"]
        self.preset = preset

    def _load_tokens(self) -> Dict[str, Any]:
        """Load tokens from file or preset."""
        if self.preset:
            from .presets import get_preset
            return get_preset(self.preset)
        elif self.input_file:
            with open(self.input_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            if "tokens" in data:
                return data
            return {"tokens": data}
        else:
            raise ValueError("Either --input or --preset must be provided")

    def _export_css(self, data: Dict[str, Any]) -> str:
        """Export as CSS custom properties."""
        tokens = data.get("tokens", {})
        lines = [
            f"/* {data.get('name', 'Design System')} - CSS Custom Properties */",
            f"/* Generated by DesignPilot v1.0.0 */",
            "",
            ":root {",
        ]

        for c in tokens.get("colors", []):
            var_name = c.get("name", "").lower().replace(" ", "-")
            lines.append(f"  --color-{var_name}: {c.get('value', '')};")
            for vk, vv in c.get("variants", {}).items():
                lines.append(f"  --color-{var_name}-{vk}: {vv};")

        for t in tokens.get("typography", []):
            var_name = t.get("name", "").lower().replace(" ", "-")
            if t.get("family"):
                lines.append(f"  --font-{var_name}-family: {t['family']};")
            if t.get("size"):
                lines.append(f"  --font-{var_name}-size: {t['size']};")
            if t.get("weight"):
                lines.append(f"  --font-{var_name}-weight: {t['weight']};")
            if t.get("line_height"):
                lines.append(f"  --font-{var_name}-line-height: {t['line_height']};")
            if t.get("letter_spacing"):
                lines.append(f"  --font-{var_name}-letter-spacing: {t['letter_spacing']};")

        for s in tokens.get("spacing", []):
            var_name = s.get("name", "").lower().replace(" ", "-")
            lines.append(f"  --spacing-{var_name}: {s.get('value', '')};")

        for sh in tokens.get("shadows", []):
            var_name = sh.get("name", "").lower().replace(" ", "-")
            lines.append(f"  --shadow-{var_name}: {sh.get('value', '')};")

        for r in tokens.get("borderRadius", []):
            var_name = r.get("name", "").lower().replace(" ", "-")
            lines.append(f"  --radius-{var_name}: {r.get('value', '')};")

        for b in tokens.get("breakpoints", []):
            var_name = b.get("name", "").lower().replace(" ", "-")
            lines.append(f"  --breakpoint-{var_name}: {b.get('value', '')};")

        for a in tokens.get("animations", []):
            var_name = a.get("name", "").lower().replace(" ", "-")
            if a.get("duration"):
                lines.append(f"  --animation-{var_name}-duration: {a['duration']};")
            if a.get("easing"):
                lines.append(f"  --animation-{var_name}-easing: {a['easing']};")

        lines.append("}")
        return "\n".join(lines)

    def _export_json(self, data: Dict[str, Any]) -> str:
        """Export as formatted JSON."""
        return json.dumps(data, indent=2, ensure_ascii=False)

    def _export_tailwind(self, data: Dict[str, Any]) -> str:
        """Export as Tailwind CSS configuration."""
        tokens = data.get("tokens", {})
        colors = {}
        for c in tokens.get("colors", []):
            name = c.get("name", "").lower().replace(" ", "-")
            colors[name] = c.get("value", "")
            for vk, vv in c.get("variants", {}).items():
                if name not in colors or not isinstance(colors[name], dict):
                    colors[name] = {"DEFAULT": c.get("value", "")}
                colors[name][vk] = vv

        fontFamily = {}
        fontSize = {}
        fontWeight = {}
        spacing = {}
        borderRadius = {}
        boxShadow = {}
        screens = {}
        transitionDuration = {}
        transitionTimingFunction = {}

        for t in tokens.get("typography", []):
            name = t.get("name", "").lower().replace(" ", "-")
            if t.get("family"):
                fontFamily[name] = [f.strip().strip("'\"") for f in t["family"].split(",")]
            if t.get("size"):
                fontSize[name] = t["size"]
            if t.get("weight"):
                fontWeight[name] = t["weight"]

        for s in tokens.get("spacing", []):
            name = s.get("name", "").lower().replace(" ", "-")
            spacing[name] = s.get("value", "")

        for r in tokens.get("borderRadius", []):
            name = r.get("name", "").lower().replace(" ", "-")
            borderRadius[name] = r.get("value", "")

        for sh in tokens.get("shadows", []):
            name = sh.get("name", "").lower().replace(" ", "-")
            boxShadow[name] = sh.get("value", "")

        for b in tokens.get("breakpoints", []):
            name = b.get("name", "").lower().replace(" ", "-")
            screens[name] = b.get("value", "")

        for a in tokens.get("animations", []):
            name = a.get("name", "").lower().replace(" ", "-")
            if a.get("duration"):
                transitionDuration[name] = a["duration"]
            if a.get("easing"):
                transitionTimingFunction[name] = a["easing"]

        config = {
            "theme": {
                "extend": {}
            }
        }
        if colors:
            config["theme"]["extend"]["colors"] = colors
        if fontFamily:
            config["theme"]["extend"]["fontFamily"] = fontFamily
        if fontSize:
            config["theme"]["extend"]["fontSize"] = fontSize
        if fontWeight:
            config["theme"]["extend"]["fontWeight"] = fontWeight
        if spacing:
            config["theme"]["extend"]["spacing"] = spacing
        if borderRadius:
            config["theme"]["extend"]["borderRadius"] = borderRadius
        if boxShadow:
            config["theme"]["extend"]["boxShadow"] = boxShadow
        if screens:
            config["theme"]["extend"]["screens"] = screens
        if transitionDuration:
            config["theme"]["extend"]["transitionDuration"] = transitionDuration
        if transitionTimingFunction:
            config["theme"]["extend"]["transitionTimingFunction"] = transitionTimingFunction

        return f"// {data.get('name', 'Design System')} - Tailwind CSS Configuration\n// Generated by DesignPilot v1.0.0\n\nmodule.exports = {json.dumps(config, indent=2, ensure_ascii=False)};"

    def _export_scss(self, data: Dict[str, Any]) -> str:
        """Export as SCSS variables."""
        tokens = data.get("tokens", {})
        lines = [
            f"// {data.get('name', 'Design System')} - SCSS Variables",
            f"// Generated by DesignPilot v1.0.0",
            "",
        ]

        lines.append("// Colors")
        for c in tokens.get("colors", []):
            var_name = c.get("name", "").lower().replace(" ", "-").replace("-", "_")
            lines.append(f"${var_name}: {c.get('value', '')};")
            for vk, vv in c.get("variants", {}).items():
                lines.append(f"${var_name}_{vk}: {vv};")

        lines.append("\n// Typography")
        for t in tokens.get("typography", []):
            var_name = t.get("name", "").lower().replace(" ", "-").replace("-", "_")
            if t.get("family"):
                lines.append(f"${var_name}_family: {t['family']};")
            if t.get("size"):
                lines.append(f"${var_name}_size: {t['size']};")
            if t.get("weight"):
                lines.append(f"${var_name}_weight: {t['weight']};")

        lines.append("\n// Spacing")
        for s in tokens.get("spacing", []):
            var_name = s.get("name", "").lower().replace(" ", "-").replace("-", "_")
            lines.append(f"$spacing_{var_name}: {s.get('value', '')};")

        lines.append("\n// Border Radius")
        for r in tokens.get("borderRadius", []):
            var_name = r.get("name", "").lower().replace(" ", "-").replace("-", "_")
            lines.append(f"$radius_{var_name}: {r.get('value', '')};")

        lines.append("\n// Shadows")
        for sh in tokens.get("shadows", []):
            var_name = sh.get("name", "").lower().replace(" ", "-").replace("-", "_")
            lines.append(f"$shadow_{var_name}: {sh.get('value', '')};")

        return "\n".join(lines)

    def _export_less(self, data: Dict[str, Any]) -> str:
        """Export as LESS variables."""
        scss_content = self._export_scss(data)
        return scss_content.replace("// ", "// ").replace("$", "@")

    def export(self) -> Dict[str, str]:
        """Export tokens to specified formats. Returns {format: filepath}."""
        data = self._load_tokens()
        output_dir = Path(self.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        exporters = {
            "css": (self._export_css, "design-tokens.css"),
            "json": (self._export_json, "design-tokens.json"),
            "tailwind": (self._export_tailwind, "tailwind.config.js"),
            "scss": (self._export_scss, "design-tokens.scss"),
            "less": (self._export_less, "design-tokens.less"),
        }

        results = {}
        for fmt in self.formats:
            if fmt not in exporters:
                print(f"⚠️  Unsupported format: {fmt}, skipping")
                continue
            exporter, filename = exporters[fmt]
            content = exporter(data)
            filepath = output_dir / filename
            filepath.write_text(content, encoding='utf-8')
            results[fmt] = str(filepath)

        return results
